# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vN4QLg2ujqNC5NsdAOhi8rKdBzzW6kc9
"""

# app.py
import streamlit as st
import sounddevice as sd
import whisper
import numpy as np
import tempfile, scipy.io.wavfile
from search_engine import load_engine, hybrid_search, detect_language

st.set_page_config(page_title="Scheme Search", page_icon="🏛️", layout="wide")
st.title("🏛️ Government Scheme Search")
st.caption("Search in English, Hindi (हिंदी), or Kannada (ಕನ್ನಡ)")

# Load backend
df, embed_model, index, bm25 = load_engine(
    "data/finalized_data.csv",
    "scheme_embeddings.npy",
    "scheme_faiss.index"
)

# --- Text Search ---
query = st.text_input("🔍 Type your query", placeholder="e.g. Pradhan Mantri Awas Yojana")

# --- Voice Search ---
st.markdown("**Or use voice search:**")
if st.button("🎙️ Record (5 seconds)"):
    with st.spinner("Recording..."):
        audio = sd.rec(int(5 * 16000), samplerate=16000, channels=1, dtype='int16')
        sd.wait()
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
        scipy.io.wavfile.write(f.name, 16000, audio)
        stt = whisper.load_model("medium")
        result = stt.transcribe(f.name)
        query = result["text"]
        st.success(f"Heard: **{query}**")

# --- Show Results ---
if query:
    lang = detect_language(query)
    lang_label = {"en": "English 🇬🇧", "hi": "Hindi 🇮🇳", "kn": "Kannada 🇮🇳"}.get(lang)
    st.info(f"Detected language: {lang_label}")

    results = hybrid_search(query, df, embed_model, index, bm25)

    for i, row in results.iterrows():
        with st.expander(f"**{row['scheme_name']}** — Score: {row['similarity']:.2f}"):
            st.write(row.get("description", ""))
            if row.get("url"):
                st.link_button("View Scheme →", row["url"])